name: aqua
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.3.0+27

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  amplitude_flutter: ^2.2.0
  flutter:
    sdk: flutter
  firebase_analytics: ^5.0.16
  firebase_auth: ^0.16.1
  flutter_launcher_icons: ^0.7.4
  package_info: ^0.4.1
  poker: 0.0.13
  sentry: ^3.0.1
  shared_preferences: ^0.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.3


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # assets:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: AquaIcons
      fonts:
        - asset: assets/fonts/AquaIcons.ttf
    - family: Icons
      fonts:
        - asset: assets/fonts/Icons.ttf
    - family: Work Sans
      fonts:
        # - asset: assets/fonts/WorkSans-Thin.ttf
        #   weight: 100
        # - asset: assets/fonts/WorkSans-ThinItalic.ttf
        #   weight: 100
        #   style: italic
        # - asset: assets/fonts/WorkSans-ExtraLight.ttf
        #   weight: 200
        # - asset: assets/fonts/WorkSans-ExtraLightItalic.ttf
        #   weight: 200
        #   style: italic
        # - asset: assets/fonts/WorkSans-Light.ttf
        #   weight: 300
        # - asset: assets/fonts/WorkSans-LightItalic.ttf
        #   weight: 300
        #   style: italic
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 400
        # - asset: assets/fonts/WorkSans-Italic.ttf
        #   weight: 400
        #   style: italic
        # - asset: assets/fonts/WorkSans-Medium.ttf
        #   weight: 500
        # - asset: assets/fonts/WorkSans-MediumItalic.ttf
        #   weight: 500
        #   style: italic
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        # - asset: assets/fonts/WorkSans-SemiBoldItalic.ttf
        #   weight: 600
        #   style: italic
        # - asset: assets/fonts/WorkSans-Bold.ttf
        #   weight: 700
        # - asset: assets/fonts/WorkSans-BoldItalic.ttf
        #   weight: 700
        #   style: italic
        # - asset: assets/fonts/WorkSans-ExtraBold.ttf
        #   weight: 800
        # - asset: assets/fonts/WorkSans-ExtraBoldItalic.ttf
        #   weight: 800
        #   style: italic
        # - asset: assets/fonts/WorkSans-Black.ttf
        #   weight: 900
        # - asset: assets/fonts/WorkSans-BlackItalic.ttf
        #   weight: 900
        #   style: italic
    # - family: Source Code Pro
    #   fonts:
        # - asset: assets/fonts/SourceCodePro-ExtraLight.ttf
        #   weight: 200
        # - asset: assets/fonts/SourceCodePro-ExtraLightItalic.ttf
        #   weight: 200
        #   style: italic
        # - asset: assets/fonts/SourceCodePro-Light.ttf
        #   weight: 300
        # - asset: assets/fonts/SourceCodePro-LightItalic.ttf
        #   weight: 300
        #   style: italic
        # - asset: assets/fonts/SourceCodePro-Regular.ttf
        #   weight: 400
        # - asset: assets/fonts/SourceCodePro-Italic.ttf
        #   weight: 400
        #   style: italic
        # - asset: assets/fonts/SourceCodePro-Medium.ttf
        #   weight: 500
        # - asset: assets/fonts/SourceCodePro-MediumItalic.ttf
        #   weight: 500
        #   style: italic
        # - asset: assets/fonts/SourceCodePro-SemiBold.ttf
        #   weight: 600
        # - asset: assets/fonts/SourceCodePro-SemiBoldItalic.ttf
        #   weight: 600
        #   style: italic
        # - asset: assets/fonts/SourceCodePro-Bold.ttf
        #   weight: 700
        # - asset: assets/fonts/SourceCodePro-BoldItalic.ttf
        #   weight: 700
        #   style: italic
        # - asset: assets/fonts/SourceCodePro-BlackItalic.ttf
        #   weight: 900
        #   style: italic
        # - asset: assets/fonts/SourceCodePro-Black.ttf
        #   weight: 900
    - family: Poppins
      fonts:
        # - asset: assets/fonts/Poppins-Thin.ttf
        #   weight: 100
        # - asset: assets/fonts/Poppins-ThinItalic.ttf
        #   weight: 100
        #   style: italic
        # - asset: assets/fonts/Poppins-ExtraLight.ttf
        #   weight: 200
        # - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        #   weight: 200
        #   style: italic
        # - asset: assets/fonts/Poppins-Light.ttf
        #   weight: 300
        # - asset: assets/fonts/Poppins-LightItalic.ttf
        #   weight: 300
        #   style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        # - asset: assets/fonts/Poppins-Italic.ttf
        #   weight: 400
        #   style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        # - asset: assets/fonts/Poppins-MediumItalic.ttf
        #   weight: 500
        #   style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        # - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        #   weight: 600
        #   style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        # - asset: assets/fonts/Poppins-BoldItalic.ttf
        #   weight: 700
        #   style: italic
        # - asset: assets/fonts/Poppins-ExtraBold.ttf
        #   weight: 800
        # - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        #   weight: 800
        #   style: italic
        # - asset: assets/fonts/Poppins-Black.ttf
        #   weight: 900
        # - asset: assets/fonts/Poppins-BlackItalic.ttf
        #   weight: 900
        #   style: italic

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/launcher-icon/icon@1024px.png"
  adaptive_icon_background: "assets/launcher-icon/adaptive-icon-background@432px.png"
  adaptive_icon_foreground: "assets/launcher-icon/adaptive-icon-foreground@432px.png"
