import "package:poker/poker.dart";

final handRangeComponentsInStrongnessOrder = [
  HandRangePart(high: Rank.ace, kicker: Rank.ace),
  HandRangePart(high: Rank.king, kicker: Rank.king),
  HandRangePart(high: Rank.queen, kicker: Rank.queen),
  HandRangePart(high: Rank.jack, kicker: Rank.jack),
  HandRangePart(high: Rank.ten, kicker: Rank.ten),
  HandRangePart(high: Rank.nine, kicker: Rank.nine),
  HandRangePart(high: Rank.eight, kicker: Rank.eight),
  HandRangePart(high: Rank.ace, kicker: Rank.king, isSuited: true),
  HandRangePart(high: Rank.seven, kicker: Rank.seven),
  HandRangePart(high: Rank.ace, kicker: Rank.queen, isSuited: true),
  HandRangePart(high: Rank.ace, kicker: Rank.king),
  HandRangePart(high: Rank.ace, kicker: Rank.jack, isSuited: true),
  HandRangePart(high: Rank.ace, kicker: Rank.ten, isSuited: true),
  HandRangePart(high: Rank.ace, kicker: Rank.queen),
  HandRangePart(high: Rank.ace, kicker: Rank.jack),
  HandRangePart(high: Rank.king, kicker: Rank.queen, isSuited: true),
  HandRangePart(high: Rank.six, kicker: Rank.six),
  HandRangePart(high: Rank.ace, kicker: Rank.nine, isSuited: true),
  HandRangePart(high: Rank.ace, kicker: Rank.ten),
  HandRangePart(high: Rank.king, kicker: Rank.jack, isSuited: true),
  HandRangePart(high: Rank.ace, kicker: Rank.eight, isSuited: true),
  HandRangePart(high: Rank.king, kicker: Rank.ten, isSuited: true),
  HandRangePart(high: Rank.king, kicker: Rank.queen),
  HandRangePart(high: Rank.ace, kicker: Rank.seven, isSuited: true),
  HandRangePart(high: Rank.ace, kicker: Rank.nine),
  HandRangePart(high: Rank.king, kicker: Rank.jack),
  HandRangePart(high: Rank.queen, kicker: Rank.jack, isSuited: true),
  HandRangePart(high: Rank.five, kicker: Rank.five),
  HandRangePart(high: Rank.ace, kicker: Rank.eight),
  HandRangePart(high: Rank.ace, kicker: Rank.six, isSuited: true),
  HandRangePart(high: Rank.king, kicker: Rank.nine, isSuited: true),
  HandRangePart(high: Rank.ace, kicker: Rank.five, isSuited: true),
  HandRangePart(high: Rank.king, kicker: Rank.ten),
  HandRangePart(high: Rank.queen, kicker: Rank.ten, isSuited: true),
  HandRangePart(high: Rank.ace, kicker: Rank.seven),
  HandRangePart(high: Rank.ace, kicker: Rank.four, isSuited: true),
  HandRangePart(high: Rank.king, kicker: Rank.eight, isSuited: true),
  HandRangePart(high: Rank.queen, kicker: Rank.jack),
  HandRangePart(high: Rank.ace, kicker: Rank.three, isSuited: true),
  HandRangePart(high: Rank.king, kicker: Rank.nine),
  HandRangePart(high: Rank.queen, kicker: Rank.nine, isSuited: true),
  HandRangePart(high: Rank.ace, kicker: Rank.six),
  HandRangePart(high: Rank.king, kicker: Rank.seven, isSuited: true),
  HandRangePart(high: Rank.ace, kicker: Rank.five),
  HandRangePart(high: Rank.jack, kicker: Rank.ten, isSuited: true),
  HandRangePart(high: Rank.queen, kicker: Rank.ten),
  HandRangePart(high: Rank.ace, kicker: Rank.deuce, isSuited: true),
  HandRangePart(high: Rank.four, kicker: Rank.four),
  HandRangePart(high: Rank.king, kicker: Rank.six, isSuited: true),
  HandRangePart(high: Rank.ace, kicker: Rank.four),
  HandRangePart(high: Rank.king, kicker: Rank.eight),
  HandRangePart(high: Rank.queen, kicker: Rank.eight, isSuited: true),
  HandRangePart(high: Rank.king, kicker: Rank.five, isSuited: true),
  HandRangePart(high: Rank.jack, kicker: Rank.nine, isSuited: true),
  HandRangePart(high: Rank.ace, kicker: Rank.three),
  HandRangePart(high: Rank.queen, kicker: Rank.nine),
  HandRangePart(high: Rank.king, kicker: Rank.seven),
  HandRangePart(high: Rank.jack, kicker: Rank.ten),
  HandRangePart(high: Rank.king, kicker: Rank.four, isSuited: true),
  HandRangePart(high: Rank.ace, kicker: Rank.deuce),
  HandRangePart(high: Rank.queen, kicker: Rank.seven, isSuited: true),
  HandRangePart(high: Rank.king, kicker: Rank.six),
  HandRangePart(high: Rank.ten, kicker: Rank.nine, isSuited: true),
  HandRangePart(high: Rank.jack, kicker: Rank.eight, isSuited: true),
  HandRangePart(high: Rank.king, kicker: Rank.three, isSuited: true),
  HandRangePart(high: Rank.queen, kicker: Rank.eight),
  HandRangePart(high: Rank.queen, kicker: Rank.six, isSuited: true),
  HandRangePart(high: Rank.three, kicker: Rank.three),
  HandRangePart(high: Rank.jack, kicker: Rank.nine),
  HandRangePart(high: Rank.king, kicker: Rank.five),
  HandRangePart(high: Rank.king, kicker: Rank.deuce, isSuited: true),
  HandRangePart(high: Rank.queen, kicker: Rank.five, isSuited: true),
  HandRangePart(high: Rank.ten, kicker: Rank.eight, isSuited: true),
  HandRangePart(high: Rank.jack, kicker: Rank.seven, isSuited: true),
  HandRangePart(high: Rank.king, kicker: Rank.four),
  HandRangePart(high: Rank.queen, kicker: Rank.seven),
  HandRangePart(high: Rank.queen, kicker: Rank.four, isSuited: true),
  HandRangePart(high: Rank.jack, kicker: Rank.eight),
  HandRangePart(high: Rank.ten, kicker: Rank.nine),
  HandRangePart(high: Rank.king, kicker: Rank.three),
  HandRangePart(high: Rank.queen, kicker: Rank.six),
  HandRangePart(high: Rank.nine, kicker: Rank.eight, isSuited: true),
  HandRangePart(high: Rank.ten, kicker: Rank.seven, isSuited: true),
  HandRangePart(high: Rank.jack, kicker: Rank.six, isSuited: true),
  HandRangePart(high: Rank.queen, kicker: Rank.three, isSuited: true),
  HandRangePart(high: Rank.deuce, kicker: Rank.deuce),
  HandRangePart(high: Rank.king, kicker: Rank.deuce),
  HandRangePart(high: Rank.queen, kicker: Rank.five),
  HandRangePart(high: Rank.jack, kicker: Rank.five, isSuited: true),
  HandRangePart(high: Rank.ten, kicker: Rank.eight),
  HandRangePart(high: Rank.queen, kicker: Rank.deuce, isSuited: true),
  HandRangePart(high: Rank.jack, kicker: Rank.seven),
  HandRangePart(high: Rank.nine, kicker: Rank.seven, isSuited: true),
  HandRangePart(high: Rank.ten, kicker: Rank.six, isSuited: true),
  HandRangePart(high: Rank.queen, kicker: Rank.four),
  HandRangePart(high: Rank.jack, kicker: Rank.four, isSuited: true),
  HandRangePart(high: Rank.nine, kicker: Rank.eight),
  HandRangePart(high: Rank.ten, kicker: Rank.seven),
  HandRangePart(high: Rank.eight, kicker: Rank.seven, isSuited: true),
  HandRangePart(high: Rank.queen, kicker: Rank.three),
  HandRangePart(high: Rank.jack, kicker: Rank.six),
  HandRangePart(high: Rank.jack, kicker: Rank.three, isSuited: true),
  HandRangePart(high: Rank.nine, kicker: Rank.six, isSuited: true),
  HandRangePart(high: Rank.ten, kicker: Rank.five, isSuited: true),
  HandRangePart(high: Rank.jack, kicker: Rank.five),
  HandRangePart(high: Rank.jack, kicker: Rank.deuce, isSuited: true),
  HandRangePart(high: Rank.queen, kicker: Rank.deuce),
  HandRangePart(high: Rank.nine, kicker: Rank.seven),
  HandRangePart(high: Rank.eight, kicker: Rank.six, isSuited: true),
  HandRangePart(high: Rank.ten, kicker: Rank.four, isSuited: true),
  HandRangePart(high: Rank.ten, kicker: Rank.six),
  HandRangePart(high: Rank.jack, kicker: Rank.four),
  HandRangePart(high: Rank.nine, kicker: Rank.five, isSuited: true),
  HandRangePart(high: Rank.seven, kicker: Rank.six, isSuited: true),
  HandRangePart(high: Rank.ten, kicker: Rank.three, isSuited: true),
  HandRangePart(high: Rank.eight, kicker: Rank.seven),
  HandRangePart(high: Rank.jack, kicker: Rank.three),
  HandRangePart(high: Rank.nine, kicker: Rank.six),
  HandRangePart(high: Rank.eight, kicker: Rank.five, isSuited: true),
  HandRangePart(high: Rank.ten, kicker: Rank.deuce, isSuited: true),
  HandRangePart(high: Rank.ten, kicker: Rank.five),
  HandRangePart(high: Rank.jack, kicker: Rank.deuce),
  HandRangePart(high: Rank.nine, kicker: Rank.four, isSuited: true),
  HandRangePart(high: Rank.seven, kicker: Rank.five, isSuited: true),
  HandRangePart(high: Rank.eight, kicker: Rank.six),
  HandRangePart(high: Rank.ten, kicker: Rank.four),
  HandRangePart(high: Rank.nine, kicker: Rank.three, isSuited: true),
  HandRangePart(high: Rank.six, kicker: Rank.five, isSuited: true),
  HandRangePart(high: Rank.nine, kicker: Rank.five),
  HandRangePart(high: Rank.eight, kicker: Rank.four, isSuited: true),
  HandRangePart(high: Rank.seven, kicker: Rank.six),
  HandRangePart(high: Rank.ten, kicker: Rank.three),
  HandRangePart(high: Rank.nine, kicker: Rank.deuce, isSuited: true),
  HandRangePart(high: Rank.seven, kicker: Rank.four, isSuited: true),
  HandRangePart(high: Rank.eight, kicker: Rank.five),
  HandRangePart(high: Rank.ten, kicker: Rank.deuce),
  HandRangePart(high: Rank.six, kicker: Rank.four, isSuited: true),
  HandRangePart(high: Rank.five, kicker: Rank.four, isSuited: true),
  HandRangePart(high: Rank.eight, kicker: Rank.three, isSuited: true),
  HandRangePart(high: Rank.seven, kicker: Rank.five),
  HandRangePart(high: Rank.nine, kicker: Rank.four),
  HandRangePart(high: Rank.eight, kicker: Rank.deuce, isSuited: true),
  HandRangePart(high: Rank.six, kicker: Rank.five),
  HandRangePart(high: Rank.seven, kicker: Rank.three, isSuited: true),
  HandRangePart(high: Rank.nine, kicker: Rank.three),
  HandRangePart(high: Rank.eight, kicker: Rank.four),
  HandRangePart(high: Rank.six, kicker: Rank.three, isSuited: true),
  HandRangePart(high: Rank.five, kicker: Rank.three, isSuited: true),
  HandRangePart(high: Rank.nine, kicker: Rank.deuce),
  HandRangePart(high: Rank.seven, kicker: Rank.four),
  HandRangePart(high: Rank.seven, kicker: Rank.deuce, isSuited: true),
  HandRangePart(high: Rank.six, kicker: Rank.four),
  HandRangePart(high: Rank.four, kicker: Rank.three, isSuited: true),
  HandRangePart(high: Rank.five, kicker: Rank.four),
  HandRangePart(high: Rank.eight, kicker: Rank.three),
  HandRangePart(high: Rank.six, kicker: Rank.deuce, isSuited: true),
  HandRangePart(high: Rank.five, kicker: Rank.deuce, isSuited: true),
  HandRangePart(high: Rank.eight, kicker: Rank.deuce),
  HandRangePart(high: Rank.seven, kicker: Rank.three),
  HandRangePart(high: Rank.four, kicker: Rank.deuce, isSuited: true),
  HandRangePart(high: Rank.six, kicker: Rank.three),
  HandRangePart(high: Rank.five, kicker: Rank.three),
  HandRangePart(high: Rank.three, kicker: Rank.deuce, isSuited: true),
  HandRangePart(high: Rank.seven, kicker: Rank.deuce),
  HandRangePart(high: Rank.four, kicker: Rank.three),
  HandRangePart(high: Rank.six, kicker: Rank.deuce),
  HandRangePart(high: Rank.five, kicker: Rank.deuce),
  HandRangePart(high: Rank.four, kicker: Rank.deuce),
  HandRangePart(high: Rank.three, kicker: Rank.deuce),
];
